package testinfrastructure;

import com.hanfak.domain.cards.Card;

import java.util.Arrays;
import java.util.List;

import static testinfrastructure.CardsExamples.*;

// TODO use interface???
// TODO better names and separate into groups of best hands
public class HandsExamples {
    public static final List<Card> PLAYER_ONE_HIGH_CARD_CARDS_ONE = Arrays.asList(ACE_OF_SPADES, SIX_OF_HEARTS, FOUR_OF_DIAMONDS, THREE_OF_SPADES, TWO_OF_SPADES);
    public static final List<Card> PLAYER_WITH_HIGH_CARD_CARDS_TWO = Arrays.asList(KING_OF_SPADES, JACK_OF_DIAMONDS, NINE_OF_DIAMONDS, EIGHT_OF_SPADES, THREE_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_HIGH_CARD_CARDS_THREE = Arrays.asList(ACE_OF_HEARTS, SIX_OF_HEARTS, FOUR_OF_DIAMONDS, THREE_OF_SPADES, TWO_OF_SPADES);
    public static final List<Card> PLAYER_WITH_HIGH_CARD_CARDS_FOUR = Arrays.asList(ACE_OF_SPADES, JACK_OF_DIAMONDS, FOUR_OF_CLUBS, THREE_OF_DIAMONDS, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_HIGH_CARD_CARDS_FIVE = Arrays.asList(ACE_OF_SPADES, EIGHT_OF_SPADES, FOUR_OF_DIAMONDS, THREE_OF_SPADES, TWO_OF_SPADES);
    public static final List<Card> PLAYER_WITH_HIGH_CARD_CARDS_SIX = Arrays.asList(ACE_OF_HEARTS, SIX_OF_HEARTS, FOUR_OF_CLUBS, THREE_OF_DIAMONDS, TWO_OF_SPADES);
    public static final List<Card> PLAYER_WITH_HIGH_CARD_CARDS_SEVEN = Arrays.asList(ACE_OF_SPADES, SIX_OF_SPADES, FOUR_OF_DIAMONDS, THREE_OF_SPADES, TWO_OF_SPADES);

    public static final List<Card> PLAYER_WITH_PAIR_CARDS_ONE = Arrays.asList(KING_OF_SPADES, FIVE_OF_SPADES, FIVE_OF_HEARTS, FOUR_OF_CLUBS, THREE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_PAIR_CARDS_TWO = Arrays.asList(KING_OF_SPADES, NINE_OF_DIAMONDS, FIVE_OF_HEARTS, FIVE_OF_SPADES, THREE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_PAIR_CARDS_THREE = Arrays.asList(KING_OF_HEARTS, EIGHT_OF_DIAMONDS, EIGHT_OF_SPADES, FOUR_OF_DIAMONDS, TWO_OF_SPADES);
    public static final List<Card> PLAYER_WITH_PAIR_CARDS_FOUR = Arrays.asList(KING_OF_DIAMONDS, EIGHT_OF_CLUBS, EIGHT_OF_HEARTS, FOUR_OF_CLUBS, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_PAIR_CARDS_FIVE = Arrays.asList(QUEEN_OF_SPADES, FIVE_OF_CLUBS, FIVE_OF_DIAMONDS, FOUR_OF_CLUBS, THREE_OF_SPADES);


    public static final List<Card> PLAYER_WITH_TWO_PAIR_CARDS_ONE = Arrays.asList(FIVE_OF_SPADES, FIVE_OF_HEARTS, FOUR_OF_CLUBS, FOUR_OF_DIAMONDS, THREE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_TWO_PAIR_CARDS_TWO = Arrays.asList(KING_OF_SPADES, EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS, FOUR_OF_CLUBS, FOUR_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_TWO_PAIR_CARDS_THREE = Arrays.asList(EIGHT_OF_HEARTS, EIGHT_OF_SPADES, FOUR_OF_HEARTS, FOUR_OF_SPADES, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_TWO_PAIR_CARDS_FOUR = Arrays.asList(EIGHT_OF_HEARTS, EIGHT_OF_SPADES, FIVE_OF_HEARTS, FIVE_OF_SPADES, THREE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_TWO_PAIR_CARDS_FIVE = Arrays.asList(KING_OF_HEARTS, EIGHT_OF_HEARTS, EIGHT_OF_SPADES, FOUR_OF_HEARTS, FOUR_OF_SPADES);

    public static final List<Card> PLAYER_WITH_THREE_OF_A_KIND_CARDS_ONE = Arrays.asList(ACE_OF_DIAMONDS, FIVE_OF_SPADES, FIVE_OF_HEARTS, FIVE_OF_DIAMONDS, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_THREE_OF_A_KIND_CARDS_TWO = Arrays.asList(FOUR_OF_SPADES, FOUR_OF_DIAMONDS, FOUR_OF_HEARTS, FIVE_OF_DIAMONDS, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_THREE_OF_A_KIND_CARDS_THREE = Arrays.asList(FOUR_OF_SPADES, FOUR_OF_DIAMONDS, FOUR_OF_HEARTS, FIVE_OF_DIAMONDS, THREE_OF_SPADES);

    public static final List<Card> PLAYER_WITH_STRAIGHT_ONE = Arrays.asList(ACE_OF_HEARTS, KING_OF_SPADES, QUEEN_OF_SPADES, JACK_OF_DIAMONDS, TEN_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_STRAIGHT_TWO = Arrays.asList(FIVE_OF_DIAMONDS, FOUR_OF_CLUBS, THREE_OF_DIAMONDS, TWO_OF_HEARTS,ACE_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_STRAIGHT_THREE = Arrays.asList(SIX_OF_HEARTS, FIVE_OF_DIAMONDS, FOUR_OF_CLUBS, THREE_OF_DIAMONDS, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_NOT_A_STRAIGHT_ONE = Arrays.asList(SIX_OF_HEARTS, FIVE_OF_DIAMONDS, FIVE_OF_SPADES, THREE_OF_DIAMONDS, TWO_OF_HEARTS);
    public static final List<Card> PLAYER_WITH_NOT_A_STRAIGHT_TWO = Arrays.asList(ACE_OF_HEARTS, KING_OF_SPADES, QUEEN_OF_SPADES, THREE_OF_DIAMONDS, TWO_OF_HEARTS);

    public static final List<Card> PLAYER_WITH_FULL_HOUSE_CARDS_ONE = Arrays.asList(FOUR_OF_DIAMONDS, FOUR_OF_HEARTS, FOUR_OF_SPADES, EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_FULL_HOUSE_CARDS_TWO = Arrays.asList(FIVE_OF_DIAMONDS, FIVE_OF_CLUBS, FIVE_OF_SPADES, EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_FULL_HOUSE_CARDS_THREE = Arrays.asList(FIVE_OF_DIAMONDS, FIVE_OF_CLUBS, FIVE_OF_SPADES, ACE_OF_SPADES, ACE_OF_DIAMONDS);

    public static final List<Card> PLAYER_WITH_FLUSH_ONE = Arrays.asList(FIVE_OF_DIAMONDS, JACK_OF_DIAMONDS, THREE_OF_DIAMONDS, KING_OF_DIAMONDS, NINE_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_FLUSH_TWO = Arrays.asList(FIVE_OF_DIAMONDS, JACK_OF_DIAMONDS, THREE_OF_DIAMONDS, ACE_OF_DIAMONDS, NINE_OF_DIAMONDS);
    public static final List<Card> PLAYER_WITH_FLUSH_THREE = Arrays.asList(FIVE_OF_DIAMONDS, JACK_OF_DIAMONDS, FOUR_OF_DIAMONDS, ACE_OF_DIAMONDS, NINE_OF_DIAMONDS);

    public static final List<Card> PLAYER_WITH_FOUR_OF_KIND_ONE = Arrays.asList(JACK_OF_DIAMONDS,  FIVE_OF_CLUBS, FIVE_OF_DIAMONDS, FIVE_OF_HEARTS, FIVE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_FOUR_OF_KIND_TWO = Arrays.asList(JACK_OF_DIAMONDS,  FOUR_OF_DIAMONDS, FOUR_OF_HEARTS, FOUR_OF_SPADES, FOUR_OF_CLUBS);
    public static final List<Card> PLAYER_WITH_FOUR_OF_KIND_THREE = Arrays.asList(KING_OF_DIAMONDS,  FOUR_OF_DIAMONDS, FOUR_OF_HEARTS, FOUR_OF_SPADES, FOUR_OF_CLUBS);

    public static final List<Card> PLAYER_WITH_STRAIGHT_FLUSH_ONE = Arrays.asList(ACE_OF_SPADES, KING_OF_SPADES, QUEEN_OF_SPADES, JACK_OF_SPADES, TEN_OF_SPADES);
    public static final List<Card> PLAYER_WITH_STRAIGHT_FLUSH_TWO = Arrays.asList(FIVE_OF_SPADES, FOUR_OF_SPADES, THREE_OF_SPADES, TWO_OF_SPADES, ACE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_STRAIGHT_FLUSH_THREE = Arrays.asList(SEVEN_OF_SPADES, SIX_OF_SPADES, FIVE_OF_SPADES, FOUR_OF_SPADES, THREE_OF_SPADES);
    public static final List<Card> PLAYER_WITH_STRAIGHT_FLUSH_FOUR = Arrays.asList(QUEEN_OF_SPADES, JACK_OF_SPADES, TEN_OF_SPADES, NINE_OF_SPADES, EIGHT_OF_SPADES);

}
